### ISSUE TITLE
Can I include your work in spicy-analyzers?

### ISSUE THREAD

**Issue by keithjjones** [r-franke/spicy_stun#1]
Hello,

I've written a few spicy analyzers and could help get the parts you have working (and add anything that might not be working) here into spicy-analyzers:

https://github.com/zeek/spicy-analyzers/issues/65

Let me know if that would be an issue?  Thanks!

Take care,
Keith

**Comment by r-franke** [comment]
Hey Keith,

Sure you can and thanks for asking. I unfortunately don't have enough time to continue working on it right now.

**Comment by keithjjones** [comment]
Not a problem!  I will play with what is here, reference the original source, get it working, and post something here when it's finished so you can use it too through spicy-analyzers.  Thanks!

**Comment by keithjjones** [comment]
MR link above.  Thanks!

**Comment by keithjjones** [comment]
Your code was merged into spicy-analyzers.  I added the TCP version of STUN to it as well since it was the same packet structure.  Thanks for getting most of the work done!

**Comment by r-franke** [comment]
Wow, you worked fast, nice work!
